### ISSUE TITLE
Video tutorial on creating the board?

### ISSUE THREAD

**Issue by s5bug** [NicoHood/Nintendo#24]
I'm having difficulty understanding how the different parts of the wiki correlate to each other. A video tutorial on how to assemble the board would be helpful in this regard (as well as links to where to buy the recommended additional parts).

**Comment by NicoHood** [comment]
Well most information in the wiki is just a documentation of the protocol. Since there are not many sources available in the web, I've added some information there. You mainly need to look at the fritzing diagram and wire the cables accordingly. And a logic level shifter is needed. Pretty basic stuff.

If someone made a video, please let me know, so I can link it.
